# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01fd9489da40c09f782d8c6877889666c79881fd296cdb745928f8505f2f4b23ffcc332bb8ac91cf06db78d25f13a71953cbcfc8e9800a9e5e9f891b9a541e30

test:
  secret_key_base: 257a6241b8b148e62539beed1129db67b5e3e250115e8d9ab6ba33070940eba3e1ebbb333b86c83e6bac0379a2706763db837744fe9a2c40b66754e8a4cfda04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
